apiVersion: policy/v1beta1
kind: PodSecurityPolicy 
metadata:
  name: my-psp
spec:
  privileged: false
  runAsUser:
    rule: RunAsAny
--- 
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata: 
  name: cr-use-psp-psp-nonpriv
rules:
- apiGroups: ['policy']
  resources: ['podsecuritypolicies']
  verbs: ['use']
  resourceNames:
  - my-psp
--- 
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata: 
  name: rb-psp-test 
  namespace: psp-test 
roleRef: 
  kind: ClusterRole 
  name: cr-use-psp-psp-nonpriv
  apiGroup: rbac.authorization.k8s.io 
subjects: 
- kind: ServiceAccount
  name: psp-test-sa
  namespace: psp-test 