apiVersion: v1
kind: Secret
metadata:
  name: accounts-secret-tls
  namespace: accounts
type: kubernetes.io/tls
data:
  tls.crt: |
    LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUREekNDQWZlZ0F3SUJBZ0lVSnAwK0dxOFZw
    UmMzNG1udUI4azNxdW9Rc0lVd0RRWUpLb1pJaHZjTkFRRUwKQlFBd0Z6RVZNQk1HQTFVRUF3d01Z
    V05qYjNWdWRITXVjM1pqTUI0WERUSXpNRGd4TVRFM05UUXlOVm9YRFRJegpNRGt4TURFM05UUXlO
    Vm93RnpFVk1CTUdBMVVFQXd3TVlXTmpiM1Z1ZEhNdWMzWmpNSUlCSWpBTkJna3Foa2lHCjl3MEJB
    UUVGQUFPQ0FROEFNSUlCQ2dLQ0FRRUE1L24xdEd0VitCaWZoekhWUFhnWGVBR2ZjNEZ4SnZRbGxB
    TVUKRGs3aWtHUVRTZlBlMnp2UngyL2IyNWhweTdGcUNmS0xzQ1VpOWdBbGZzNENTQVlEQkp5a1E2
    V056TVBhU3hJdAppcFZ1WFdHZHV5YTJNc0tuNFJTc3VqM25sdk01WjNYUGhlTmh2a3RxWU5JVktu
    ZVFJSVBrbXB0OFZzajdQVFNjCmFwY3FWQnF0Tm5jT09CbENEZzgxL0JveEx4RnVqNU1EZjVzL01i
    MEprOUNoVFB3d2VRdC9ERVF1TWxMQVdFUUQKOWtBUktsUXJTMkZQZm1lSGUwMVhGQnE1Z3hmUjdW
    bGdKV3pMSnl0ZlNyU0ZlcXd2blpBQ1BnZk9iaHJ6aEQ4ZQpYS1JaUEh6ZEZlNEhzZTZKKzJDbnIr
    UWU4cDV2bjllTHhWbVc1QUhtekZDS0ZyckI2UUlEQVFBQm8xTXdVVEFkCkJnTlZIUTRFRmdRVTZF
    ZUhiWWFVRU9zN2d4TkxaNk4xbVpQdUdGSXdId1lEVlIwakJCZ3dGb0FVNkVlSGJZYVUKRU9zN2d4
    TkxaNk4xbVpQdUdGSXdEd1lEVlIwVEFRSC9CQVV3QXdFQi96QU5CZ2txaGtpRzl3MEJBUXNGQUFP
    QwpBUUVBejkyb2M5aTRwSmF6T3BuTlh5eWFYNXg3eG1qTVJlRzRGZXJ1UWFRTkNiaEtZbzRWTkQv
    eFpYZEx3Mnl5CkkvaEdiaEZsYmRVWjBmVXRRM0RSK2o0V0xPQWJYTFdzSXlKbXpMeE9nZmVGSk1m
    dXNkWHpOczBXMGttSkYrbEMKMSsxZkZiT01zY1lPanBsMlQ0V2dteno0TDJuYTZPVFZJWTdqU1dG
    SXNaN2Q1OVlwZ3FFaldXSjU4N2FjejdCMAoyYnpVS3JzaDhObW12bldxN29nUnQ5TmNGUGNBUDBr
    RVU0Tnd2N3hXZ0xGMmtib3p4UkxmM05DWXk1eFNBZzNqCktyb3ZOS1lMWGxSNkF1eEhudlcvakZp
    L2Fra2ZBTmltV3ZtejR5UmRhSlVRRnlJS1paR3Brb002ZGh1UUhLbUkKTlZIZEVtM2F3SGJHLy9V
    UG9OeDVyWmNHcEE9PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
  tls.key: |
    LS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0tCk1JSUV2UUlCQURBTkJna3Foa2lHOXcwQkFRRUZB
    QVNDQktjd2dnU2pBZ0VBQW9JQkFRRG4rZlcwYTFYNEdKK0gKTWRVOWVCZDRBWjl6Z1hFbTlDV1VB
    eFFPVHVLUVpCTko4OTdiTzlISGI5dmJtR25Mc1dvSjhvdXdKU0wyQUNWKwp6Z0pJQmdNRW5LUkRw
    WTNNdzlwTEVpMktsVzVkWVoyN0pyWXl3cWZoRkt5NlBlZVc4emxuZGMrRjQyRytTMnBnCjBoVXFk
    NUFnZytTYW0zeFd5UHM5Tkp4cWx5cFVHcTAyZHc0NEdVSU9Eelg4R2pFdkVXNlBrd04vbXo4eHZR
    bVQKMEtGTS9EQjVDMzhNUkM0eVVzQllSQVAyUUJFcVZDdExZVTkrWjRkN1RWY1VHcm1ERjlIdFdX
    QWxiTXNuSzE5Swp0SVY2ckMrZGtBSStCODV1R3ZPRVB4NWNwRms4Zk4wVjdnZXg3b243WUtldjVC
    N3lubStmMTR2RldaYmtBZWJNClVJb1d1c0hwQWdNQkFBRUNnZ0VBUzRvRTdieHFJVUQ3YWMzYmI0
    blVzcHBzcnZNK3duMk1ZeGRoaDRzK2tlQlUKdTZjek1kYlg2QWJQNUVGTWFpMGFwNlNZd2tKRmtT
    L1pCZUxWc1ZocjBTdWsvZlpDSjZTN1IramlkWmRWZWdrWQprT0g1UUt4TWVLbi8yU0hoY1RGQXh5
    VUE3OHRzZjhnVkd2UXVPa2IyNHUrd0dIeDdUOU5ncEx5bUZydWs1Lyt0CkhxMzhCcHZuUGo5ckQ4
    MUovaHEwVUEzQ3hnRmNRRkxPN0RSdndaTkZ2eGtlWWlhWW1oTXNaRGtyUjdmWG8vWXIKM2tIR1Yx
    ZUllQlhGQThHWllacVBmOWtPNXo5SUh3MytmbXR3K05JbVVCWlVydEkxZ2orNngrTVZVUVhUV2JN
    UAp0OTd4aE0rZ2tpSXoxRHRESzBsUXVJRk9sRW5FZVJia3YvbzhkaVBkRVFLQmdRRDNvMHJzOUFs
    Wng3bzhJVUlkClJZT25TMldPeVVyU2pUQSszQmFtQzlwTXhJMDNyVDJFT2hKWUE5ZUZ3VjhWeHh4
    VkhoTVNxOEo5YVNlMDRPVy8KcmI0d3pYOUZHNmE5SjhZMitUUHV0V0E2SHN6VGhWazE2MzJ3M25i
    OEdXa3d6ZTBnbDFIQkUrTjFQcnp2emVTVgpPWkdtNk13T253Q00xSGtvekFPNmVEMG41UUtCZ1FE
    dnowZ1NTY0xOQWJoOUQ2SUVBMmg5bzhJaDdzYTVDUDA1CmVVWEtxL2MwZDdOajBsMWxUM054ajh1
    MWI2SGJPcjgxdy9hNHpBQW1IQUV0Y0k2NTI2TDFNb0sxUUVlandvRHUKMUg3NkVWODEzNGt5dHRM
    d1VDdG9yYk5YeGl5Z2JqSllTSXpJNUx0c3orVTBCVjlVcTl4aG9GQU9Jbkh1NTNiUwprMGlNR2xT
    SnRRS0JnUUNXZ1ZrdFVGaEtoNWdKcVpEOEoxNlBrOFJpbHJaeDV6dVdTTDgvSmQ4RVgwVVF2S3F4
    CnJYV3Vwbzhiak40VVoxSXg3VGhjVmFXOEFPZ1FCOHU2eG9iY05Ga1FrSEN6Yi9RSlAwWXY0MjVi
    aEpLcVQ5WmIKYmdlVE1uSVFZQVZOa3lwMmIyRlJ2cHUwaTIvYk0wQ2s3VHMzdlM4Z0I4VVcwcC9j
    aXJvTlg3eVRmUUtCZ0FGeQo4ekNKR1pBN2ptM1RCbHVYMmEzSXE0ZWc5YnB3ZjNjMWNHS0ZIMzFG
    cStQU2haWHpJUE55dHZ4bHJFaXkxaXp3Ci9qQ25xdWlRQ3NISGlGVS9Lb0RveVRsbkpnZXJTVFFv
    UEl3dVJyRUFwTWVWcXppZ2cyS2lpZzdodDZ0UWZ5VmgKYXRoYjZYWUMyNU93NUo2U1cwYUx2WEFZ
    YlMvUVhqdHZnR1M0VkFKeEFvR0FiREFnWFdVejRUWGFlZ3dYVFh1ZApoRVVoRzU0YXZmeS9ibHVt
    RzBDZGVxRExpNnN2RFZ3amxSb1hwQkhCQnJnd0FLRk9XdlNIZ1ROMkFBZEM2T2txCkFwNDlCaU4x
    MEdWdW1JKyt3Rm04VkQ4S2NvMmhDMFhnZVkxOGNqMytHcmFYZnk0cmdSL0NzWG1lTVBBdXpmSFYK
    Y1JONXFnUTJjeGkxMTdES2lLSHVNZWs9Ci0tLS0tRU5EIFBSSVZBVEUgS0VZLS0tLS0K
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: tls-accounts-ingress
  namespace: accounts
spec:
  tls:
  - hosts:
      - accounts.svc
    secretName: accounts-secret-tls
  rules:
  - host: accounts.svc
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: accounts-svc
            port:
              number: 80