apiVersion: v1
kind: Secret
type: kubernetes.io/tls
metadata:
  name: ingress-tls
  namespace: ingresstest
data:
  tls.crt: |
    LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUREekNDQWZlZ0F3SUJBZ0lVVWZHVDErZzdo
    WTRuNjEwb3M0ZVVCOXN0djQwd0RRWUpLb1pJaHZjTkFRRUwKQlFBd0Z6RVZNQk1HQTFVRUF3d01h
    VzVuY21WemN5NTBaWE4wTUI0WERUSXpNRGd4TVRFMk1UZ3dNRm9YRFRJegpNRGt4TURFMk1UZ3dN
    Rm93RnpFVk1CTUdBMVVFQXd3TWFXNW5jbVZ6Y3k1MFpYTjBNSUlCSWpBTkJna3Foa2lHCjl3MEJB
    UUVGQUFPQ0FROEFNSUlCQ2dLQ0FRRUExQ1ZBYVNrQW5zMW9zZmVVSDA1cDV0SW81UnQzVzNiZmUv
    K20KajhUNWFXUVk1SGZrSlF0bTVTSk45aEdUWkxHYTNORkhMUUJ1OWZFRXF2VjlmRm1oN3lUdGw4
    S0NTQjJPd1VQZQpvN2t5clQxSHhNd0hxQVdQcXZ2eWpYeEhReUwxSGdsVmRWaGNFM21qRk9ZWjYr
    SmM5VU5abHRVK1l2S21xR0luClhVcXdHdzFJdk5DWk10akx0RVZpaEtmMldjNDQ0aU5qbDloN1F5
    bnBxdkh5d1BPSHFJSnRUTUtiNFM5dk9JY0EKNXByUnEveGNIaWd6eWJsZnE1L0I0SVdPSVFrazVJ
    cnBnYkhGSytYNmQzUHEzNlZCcWpqaWpHRjJpajZJT0s0agpsY01VUGNSeGwyemFyRnh0RUU3cGZE
    QUJFWFZvS2Jwd25ZTVVZZ3RMdlJVMkhPVm4zd0lEQVFBQm8xTXdVVEFkCkJnTlZIUTRFRmdRVXRn
    TmVENFRvS1Z4UG9Wa25Zdk9hN01CZFVOOHdId1lEVlIwakJCZ3dGb0FVdGdOZUQ0VG8KS1Z4UG9W
    a25Zdk9hN01CZFVOOHdEd1lEVlIwVEFRSC9CQVV3QXdFQi96QU5CZ2txaGtpRzl3MEJBUXNGQUFP
    QwpBUUVBV1V5VjIxaWxhQ3ZuT25oSWprMlRLYUNHVVRJKzBQd0p2UktDRVhPOStmTTF2WlVDajdN
    bThjSGt2OUdoCnZGZE9GTUM3SXQvM2IxRFliYzBvS0IyVEVFQUZzSFNvZHJ5SkhoTy9ublc3UW1r
    dDVHTDQwTlozZ3IrbkxXOW4KR0k3REdBb1lnVERLNEVlVUpBQ0k5V2RwRTh3SDFNZzdVd3N0dytw
    UzAycklRaVBkVWQ0SDBDV3VLM0VVRTM0bgp5MUM4M2FpQmFCMW1iY1dvd25HTFhOd3dWdVJPb21m
    MTJPUFNCcHFaZGViQmNkU3hmVlJTeDc3RVdNNlNsWno4CnBhei9nb05yd1BWRGgyeWR0TytEdkI3
    NEJxM0ZRc3NQZTlXOUp1TW5hSExqams1YWQxQ2hHUEI2WHF3WDFCZWwKR2lBUnNKMjU5dEV6bTRX
    dkhNaGlqdTdLdnc9PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==    
  tls.key: |
    LS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0tCk1JSUV2UUlCQURBTkJna3Foa2lHOXcwQkFRRUZB
    QVNDQktjd2dnU2pBZ0VBQW9JQkFRRFVKVUJwS1FDZXpXaXgKOTVRZlRtbm0waWpsRzNkYmR0OTcv
    NmFQeFBscFpCamtkK1FsQzJibElrMzJFWk5rc1pyYzBVY3RBRzcxOFFTcQo5WDE4V2FIdkpPMlh3
    b0pJSFk3QlE5Nmp1VEt0UFVmRXpBZW9CWStxKy9LTmZFZERJdlVlQ1ZWMVdGd1RlYU1VCjVobnI0
    bHoxUTFtVzFUNWk4cWFvWWlkZFNyQWJEVWk4MEpreTJNdTBSV0tFcC9aWnpqamlJMk9YMkh0REtl
    bXEKOGZMQTg0ZW9nbTFNd3B2aEwyODRod0RtbXRHci9Gd2VLRFBKdVYrcm44SGdoWTRoQ1NUa2l1
    bUJzY1VyNWZwMwpjK3JmcFVHcU9PS01ZWGFLUG9nNHJpT1Z3eFE5eEhHWGJOcXNYRzBRVHVsOE1B
    RVJkV2dwdW5DZGd4UmlDMHU5CkZUWWM1V2ZmQWdNQkFBRUNnZ0VBYXlWVlhzZUN0TEh5Q3RDTVV6
    TjdjVVQ3dXBzZ3NXVmNnbmdnVzhTVVk1SlcKc0MyTllOaGRZNlRyMHpnVlJXb2VXU0NwM2lTMTVp
    bVF2ZmUzSlRMd0FxU1lDMm9GK3Y1U3QzSGI1TDBJeDA2SQpEUEV2Zk1FeVNwMXRaK0E0N2NPZUlV
    bDlqQUxRbmxWMDlIMHk0bHcxcnZvUktZa1NOVTl3dE9LK0Z2UTk5YXJYCmlLZ0RmcEhtZmdlYlJw
    SmR5S2w4eTlNamwyaFR4dmtlTVo5UGlQSjR5aWNOMkJtZkU3RjZ2elg1NDFsOFErVlAKWlZOcFk3
    NVlWUS9tRlhYdE9VeHBZUnRjNmdIYUp1K2tyemlvb2FWYlhPVTdaditKZXFORDFxVjl3Vis5VTlq
    egpFSlVlTFFTVlZ3Z095ZlpXOXhIRk1EbE5pQXc4NmtyRnZ4VUNiWG0xQVFLQmdRRC9iZENnekQy
    TTJqUnpKVG5ZCmxRcnhiNTV6VDlOaHBvc1pOK0pKRFNMcU0yUFl1RFZyZEFjYnR0ZTg0a0pYbUpw
    andnRDd1ZXNmNXJTV3ppbnIKaHBGUDVmZHhnKzJVK1hxVTlHcXoveDdzdGFiWDZEOURmQ3B1UnZO
    Tzk4VTRxdyswM2oxdWxtRExMcU1nakJUcQo4UDVYNWxBSjQ4eUtTMy94a2ZQWHlqd2Mvd0tCZ1FE
    VW5xbytjNzVobUJmYTBHWFNrY0VLVm1ZQnJjMUVEK243Ckp0Sm1TaWFxeVV5TldRQzJidktTRGhH
    eWd4ajNreHVJZVJhTjJ2ZlR4amRYTlNsWHJsai9uUDhVMURwbFJ5bi8KNU9EQUgrM21UdzRvSHpV
    WkZSaHB6c0xlOVhBTitNOVozb1kxZDJGOCtpbDNUOGlxRGZXWGtIMkJxU1gzSnBwVApRVm8zMlh0
    VklRS0JnUURsVGQ1bkhETjlTVDZneUNDQUVIejhkZW5YTnloYWw3cHo3emxUdjFsQ3l0T3Q4T0Qw
    CkQvdDVvOUZWSGdIVXhZaUVXZHVzSUNHMlI5U0ROWjFvZFN2cWdGWjlMNlNQZ3MvSy9RajFnZWh2
    TkR3Tnc4OVgKZEJaYlhaSjdwKzhEaW4zVkwxWVMreWoxL200dmY5SWZnQzIxRjJ0dkZYUEFDenRX
    MEdJSnJPSCtYUUtCZ0VlagoxblVJaHNOWGZlSXFpY1J6ZS9uQnRza21DSjNBUnZScTFrWEZBbFpW
    VVVmbkQwaHBCYTZVc3YzVkVscUk1S1FOCk9MNC9ZM1dsdWd2V1M4SFJhd2Rsbk1VbDVTOHUxVVgx
    bG96bHRVRCtyaVJ5cjI5dUhqVzRod3ljNGs2eTRSckUKMGErK004anFlWUpNRGE3TzJVdGlVZ2VZ
    T01TWDZ6UFdOMUhPSTdKQkFvR0FaMWkxWmZXM1BNVS9pWFRHQmd2UQpYRDBaR2l0dnVwdnVTcjJP
    Q3l6SjRxazBWS3VmaXkvdHNtd0lTL09RZkpJV282ZFRnRDhVMlZaZ05LV28vU2VRCnZTN1J4RFI1
    dlJkcGI0UVdtSnh2cDFiR0NSMzhYb3V4NnFWTHAxMFZnRWZITFNqR1FNalNKL0ZaRnNsalYwYU4K
    MlVidzlDNGZJQTU3emxrc2hwbGVkWnM9Ci0tLS0tRU5EIFBSSVZBVEUgS0VZLS0tLS0K