apiVersion: v1
data:
  admin.json: |-
    {
      "mode": "DEVELOPMENT",
      "properties": {
        "secretsDir": "/var/ig/secrets"
      },
      "connectors": [
        {
          "port": 8080
        },
        {
          "port": 8443,
          "tls": "ServerTlsOptions-1"
        }
      ],
      "session": {
        "cookie": {
          "sameSite": "none",
          "secure": true
        }
      },
      "heap": [
        {
          "name": "ServerTlsOptions-1",
          "type": "ServerTlsOptions",
          "config": {
            "keyManager": {
              "type": "SecretsKeyManager",
              "config": {
                "signingSecretId": "key.manager.secret.id",
                "secretsProvider": "ServerIdentityStore"
              }
            }
          }
        },
        {
          "name": "ServerIdentityStore",
          "type": "FileSystemSecretStore",
          "config": {
            "format": "PLAIN",
            "directory": "&{secretsDir}",
            "suffix": ".pem",
            "mappings": [{
              "secretId": "key.manager.secret.id",
              "format": {
                "type": "PemPropertyFormat"
              }
            }]
          }
        }
      ]
    }
  config.json: |-
    {
        "handler": {
          "type": "DispatchHandler",
          "config": {
            "bindings": [
              {
                "condition": "${request.uri.host == env['MY_POD_IP']}",
                "handler": {
                  "name": "router-pod",
                  "type": "Router",
                  "config": {
                    "scanInterval": "disabled",
                    "directory": "${openig.configDirectory}/routes-pod"
                  }
                }
              },
              {
                "condition": "${request.uri.host != env['MY_POD_IP']}",
                "handler": {
                  "name": "router-service",
                  "type": "Router",
                  "config": {
                    "scanInterval": "disabled",
                    "directory": "${openig.configDirectory}/routes-service"
                  }
                }
              }
            ]
          }
        },
        "heap": [
          {
            "name": "JwtSession",
            "type": "JwtSession"
          },
          {
            "name": "AmService-1",
            "type": "AmService",
            "config": {
                "url": "http://am/am",
                "realm": "/",
                "agent": {
                    "username": "ig-agent",
                    "password": "password"
                },
                "sessionCache": {
                    "enabled": true
                }
            }
          },
        {
            "name": "ForgeRockClientHandler",
            "type": "ClientHandler",
            "config": {
                "trustManager": {
                    "type": "TrustAllManager"
                  }
            },
            "_capture": "all"
        }
        ],
        "monitor": true
      }
  health.json: |-
    {
        "name": "health",
        "handler": {
          "type": "StaticResponseHandler",
          "config": {
            "status": 200,
            "headers": {
              "Content-Type": [ "text/plain; charset=UTF-8" ]
            },
            "entity": "Health"
          }
        },
        "condition": "${find(request.uri.path, '^/health')}"
      }
kind: ConfigMap
metadata:
  name: ig-routes
