@Library('JenkinsSharedLibrary') _

batchPythonContainerized {
  moduleDir = 'telus-elkbackup-batch'
  repositoryUrl = 'git@bitbucket.org:telusvideoservices/telus-elkbackup-batch.git'
  gitBranchDevOps = 'main'
  cronScheduleBranch = 'release/AVS_6.6'
  repositoryUrlDevOpsOCP = 'git@bitbucket.org:telusvideoservices/telus-elkbackup-batch-devops.git'
  mavenAdditionalParams = '-P distributor'
  targetEnvironment = 'main'
}
