version: '3'
services:
  redis:
    image: redis 
    networks:
      - back-end
  db:
    image: postgres:9.4
    networks:
      - back-end
  vote:
    image: voting-app
    ports:
      - 5000:80
    networks:
      - front-end
      - back-end
    depends_on:
      - redis
  result:
    image: result-app
    ports:
      - 5001:80
    networks:
      - front-end
      - back-end  
  worker:
    image: worker
    networks:
      - front-end
      - back-end

networks:
  front-end:
  back-end: