apiVersion: v1
data: {}
kind: Secret
metadata:
  labels:
    app: ig
    app.kubernetes.io/component: ig
    app.kubernetes.io/instance: ig
    app.kubernetes.io/name: ig
    app.kubernetes.io/part-of: forgerock
    tier: middle
  name: openig-secrets-env
type: Opaque
---
apiVersion: v1
data:
  id.key.for.signing.jwt.pem: |
    -----BEGIN PRIVATE KEY-----
    MIIEvwIBADANBgkqhkiG9w0BAQEFAASCBKkwggSlAgEAAoIBAQDJ2cWKv0MyVdlh
    2GqgEYOvGoApF6X47IZT5xkBsAVG76RcE1HxR9uCCUyymX5AQEjaRb1CpHpmQg++
    N2kHYP3ePMslT5RiCOxYUPYIkgZWFmnVs+wUmT3umZea73SBR4204OC5yi5aI1Ms
    BOxNPHkH8Za0hZAXx/yPMfk6OjEaY8Fwx230WU8kdP+BVgyrGZDGIavHRqC0odLU
    Oh86w01X5+/qgYlcTXKCcrNA5ML8L+5dwGC9+G7XYCN9JZ+y24RD2T/Ylu4qZK+9
    /6rBKnWv20UN/y5M6MTlbeMceW68l8rqz+w5tetHZ8pbzvhEzXlQf77YvlbQu6Ur
    NiyonhazAgMBAAECggEBAKidbDE9GIsBv/fGazuPpesuPgUVpiXMn2GTWQZZ3e6l
    3Sy1Tuw5VJrJ3fIL2rUdfj4np7P15fFqGfCSJQBu+2Mcca6XTaKfRZ948i2ynexo
    CLzl8b47TMr2LvjUMwSTm0KP3+oThKjzfVT2P9c9PvVt0LC4KehTvRx5aHJFjiM1
    2eHlNLgtFjaE2xzppn7i5deIeWFWt9Fi/mydTQrDvtrTnFCFVaP33IpCzpmLPYLr
    fMITQNv0dUgcONiMDcmFVweddJ5Wm9rJbAVG/2Wp2M9+DQjqLW+Y8Nwyf+hyBb0G
    svo/4I5sHnGzcndCqWfefYREu3xwnjsQt4BTROnuy+ECgYEA5Z288BgX5P6wFTYi
    0E3PtImsrVElgZE8zs13dBX8VDHZVQC34sDqVpTu/BI4HMwpHnJZH0vUJQiuIrmw
    6Y09uJqtiHHRvuZWLcgBXIFNxP12CKQGhzk+ETPyxcAd8mMkjx8e4s5cMklu0GHA
    83Nua3aVrB9khgAgnkqZ2Sj4Q/kCgYEA4QtMmZyKEhj/kw6HQAcqi6Lc7lRiybbK
    x16NNAEwKP4Ei8yhAUo6+eAk0F3KvWiYCTHo/te18b5gvvKpebuyT9dsxRDrgAHF
    Zaha9wSEGmsK+YM3f5LnH/f7PY5m2RAis3jt4QQd6SXXg2L0O0FH/CJr4krczPQv
    w01iKJWxQwsCgYAYYpgeJ3DiMOoiVo178ceNNNHR1jxVdkcu70MwYOVbS6/5BwqA
    WlyItWhr/MNYy5XSVfKBEFyHUlSr+2x+YTGc2VB0nSHZVDzyv7rlSBYqRYCzijfn
    RH0C9rFhrvV/OGg5iuSM0b2Y2ZObLcaAFFI1t3JNxUe3s2vDY8jS9zbmgQKBgQCs
    kk2bPj9iwWi7DFkK8HPfwHRLDsryhAnb+NWvG3oi9SfnTHPq2VGAbDHO1x2xQZPU
    +UECq8gKKUNnKg5sG1MRhtESDXeKIdGNsxyOcBgdahhwXf8hBTXXfgJboeecbJMv
    rXw9ITsOnsY1Kpy/E8BvyLWSQnYvdNFrotuy45ebIQKBgQCOWdcpwv2LLqFkr+bg
    iNxeT/kikh2pFeRbMP3iO/VNjcrFhhaOnRuaAXpG5eBbrVNWtOSI5PkwoqxsA5Qi
    Dl0TH41hwEubO7DVUdhdQPD02LM2iAbtbY36YrcKwY0lMEtU6dXisuJkh9V11NQK
    SlnaHsDvcxolC7gMUjxQr3SWnA==
    -----END PRIVATE KEY-----
  id.key.for.verifying.jwt.pem: |
    -----BEGIN CERTIFICATE-----
    MIID5TCCAs2gAwIBAgIUeRkMu1AfaF4FdElayeNyg6+41acwDQYJKoZIhvcNAQEL
    BQAwgYExNjA0BgNVBAMMLWlnLWFsYi0xMzk5NzU1MTYwLnVzLWVhc3QtMS5lbGIu
    YW1hem9uYXdzLmNvbTESMBAGA1UECwwJYW1hem9uYXdzMQwwCgYDVQQKDANjb20x
    CzAJBgNVBAcMAmZyMQswCQYDVQQIDAJmcjELMAkGA1UEBhMCZnIwHhcNMjMwNjAx
    MTQyNzAwWhcNMzMwNTI5MTQyNzAwWjCBgTE2MDQGA1UEAwwtaWctYWxiLTEzOTk3
    NTUxNjAudXMtZWFzdC0xLmVsYi5hbWF6b25hd3MuY29tMRIwEAYDVQQLDAlhbWF6
    b25hd3MxDDAKBgNVBAoMA2NvbTELMAkGA1UEBwwCZnIxCzAJBgNVBAgMAmZyMQsw
    CQYDVQQGEwJmcjCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBAMnZxYq/
    QzJV2WHYaqARg68agCkXpfjshlPnGQGwBUbvpFwTUfFH24IJTLKZfkBASNpFvUKk
    emZCD743aQdg/d48yyVPlGII7FhQ9giSBlYWadWz7BSZPe6Zl5rvdIFHjbTg4LnK
    LlojUywE7E08eQfxlrSFkBfH/I8x+To6MRpjwXDHbfRZTyR0/4FWDKsZkMYhq8dG
    oLSh0tQ6HzrDTVfn7+qBiVxNcoJys0Dkwvwv7l3AYL34btdgI30ln7LbhEPZP9iW
    7ipkr73/qsEqda/bRQ3/LkzoxOVt4xx5bryXyurP7Dm160dnylvO+ETNeVB/vti+
    VtC7pSs2LKieFrMCAwEAAaNTMFEwHQYDVR0OBBYEFHUOmqsnKFePMZqJ8DEccsfV
    rws6MB8GA1UdIwQYMBaAFHUOmqsnKFePMZqJ8DEccsfVrws6MA8GA1UdEwEB/wQF
    MAMBAf8wDQYJKoZIhvcNAQELBQADggEBAEyOVQW7ctza74cS4ND3ZZmZWSJthSvk
    /cuY/3+4VhjEek4CNB84P+0b6nRzNahQOUR5QqejNGRAaNlfMwEykGx6JQKlT+Js
    YBMjylvm9Ct6LR7410dLtFT2fVsEJaZiHQlujTpipSLw0AcZOB9J7zXfMM4/Y0Jr
    ztx172b0Pce6Zo5v/Vy5fbvWuW7biC7u+rg+OhlXnAIhv727LAIHsrkTYdR1sGbL
    a0mk5QR+Ag2KNOr+69JPE+k6shJS6L/4dSRxtfOdD14WwxdPHRTIcTvi8/U3gLDa
    QuZcJJ0yT8T0//tb/JJISHm1UiyI43Q3YYB3BqKUSyalNiAeIuVcZbk=
    -----END CERTIFICATE-----
  ig.amazonaws.com-certificate.pem: |
    -----BEGIN CERTIFICATE-----
    MIID5TCCAs2gAwIBAgIUVK/4a0TK/7OlzcvHj28YIYor004wDQYJKoZIhvcNAQEL
    BQAwgYExNjA0BgNVBAMMLWlnLWFsYi0xMzk5NzU1MTYwLnVzLWVhc3QtMS5lbGIu
    YW1hem9uYXdzLmNvbTESMBAGA1UECwwJYW1hem9uYXdzMQwwCgYDVQQKDANjb20x
    CzAJBgNVBAcMAmZyMQswCQYDVQQIDAJmcjELMAkGA1UEBhMCZnIwHhcNMjMwNjAx
    MTQyNjExWhcNMzMwNTI5MTQyNjExWjCBgTE2MDQGA1UEAwwtaWctYWxiLTEzOTk3
    NTUxNjAudXMtZWFzdC0xLmVsYi5hbWF6b25hd3MuY29tMRIwEAYDVQQLDAlhbWF6
    b25hd3MxDDAKBgNVBAoMA2NvbTELMAkGA1UEBwwCZnIxCzAJBgNVBAgMAmZyMQsw
    CQYDVQQGEwJmcjCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBAOL+tmeD
    hmjCWuKNVWnJTPzGFGvtVgYXk4Q0329RsBszZotZCxijLzwzJVvZ13pFzSlstjJp
    5jpv03JrTH8vdxljRl5FVnS5iHuTIc3jcePEnc57M6/YvO1mP+wSULazucHHE74n
    QZBO1Gmne73oA2n7eA6sWUP4fuzj3IrQgpVX38At5oVfafH2thkQMGj7ugT0oB5i
    eulpbElrC0reDlit/MN3flI9OcY7uThiCvH5AP/i+0Z0Anzq6IdwyXfN5TZiv0Rc
    NhOvWCTo53orCmPrfMIryZ95geuVh7Y4yYtaOdcHvXIG7KFSpEQqaUnKvkx/w5+n
    zOSQ+1i2nSaO72cCAwEAAaNTMFEwHQYDVR0OBBYEFKSKY9i6NEHqxS367eVxzeYp
    9BtSMB8GA1UdIwQYMBaAFKSKY9i6NEHqxS367eVxzeYp9BtSMA8GA1UdEwEB/wQF
    MAMBAf8wDQYJKoZIhvcNAQELBQADggEBAJQHugBxgeDTjRRsQXyogO9b1GiS8Awr
    ne6Vs4OBwL2xFpqdf7vxHOxOQKutD7ZLe66dmmUjZx9P4JF/laZGsBGzV8Zwn845
    GBi7jOX6gWpGAp3A8BnEMY5FCdNT9BaLTJcSUNzrcl0D3JA1ni6KBJdNzsqR6wWX
    WAm84NHfkQ62oIz2jXFEakg2uvva5FMHZZQGLYvawJnSO6cmcgahzhVLN8uJP7hT
    X2r230fUOHnkp8OQ2PcikyEOAZ767QrY7RO2DXOEabpj0I7CRqU9rmuyr4eiaGqc
    Bwqww7+a4v/Z2kNzJZdlBlYhwqNIP7RW45cD+GDICom1PY9m3eLJemA=
    -----END CERTIFICATE-----
  ig.amazonaws.com-key.pem: |
    -----BEGIN PRIVATE KEY-----
    MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQDi/rZng4Zowlri
    jVVpyUz8xhRr7VYGF5OENN9vUbAbM2aLWQsYoy88MyVb2dd6Rc0pbLYyaeY6b9Ny
    a0x/L3cZY0ZeRVZ0uYh7kyHN43HjxJ3OezOv2LztZj/sElC2s7nBxxO+J0GQTtRp
    p3u96ANp+3gOrFlD+H7s49yK0IKVV9/ALeaFX2nx9rYZEDBo+7oE9KAeYnrpaWxJ
    awtK3g5YrfzDd35SPTnGO7k4Ygrx+QD/4vtGdAJ86uiHcMl3zeU2Yr9EXDYTr1gk
    6Od6Kwpj63zCK8mfeYHrlYe2OMmLWjnXB71yBuyhUqREKmlJyr5Mf8Ofp8zkkPtY
    tp0mju9nAgMBAAECggEBANopqg+kxiqrGQSCh6PLV9XdXkU4bqQeRqYa1t+7aAFM
    jnLBGrwMIlq+YVp87O7UZVE57YZYZ3Ckh1mBrJzUdqgM1NXH2EcJBhaWmzexMIWT
    M4P+vvdz3GhiDG+MTsy5wX9vIRdxzT6vtNDyqigj9BwJFyMrHAQKsZpliVJVAhwa
    8C0/8GVEEqCsmIsDj5ZGEcUwIc7sIdR1XSNQfpcQuZBPEOZl0E8hcqJzUWyW8SOp
    1JNy6VzVXYoG0qYAscyE2dWusGTiTDS9oAtKtj5YIRgdBHaSbie/frG6c/b8EX00
    Re/0Xp+Tg9YI9qXGCuW68A+ay8A6zm3jOuOZfFO2X8kCgYEA9uhiJo6BuHm5vQzV
    oeGOOUWIRZ/3TtaPYHxXAXDTGv2sE3SWmj/yjsFJrG98pI2bKL/itfFDesNLp6Il
    lNJ3P0Pm8w8y5WiuCvDzXEPNRAMyq65pbYFU4xyXJ9XGRc62j4FjaJZ9sk1lTGJt
    niHSFzfO19dB493tw2vAtL9kXG0CgYEA61qcJ2ee7Z9wD4NOGYSBw3A0riho1g/W
    23P/bbwErkxeh0p0HlBD/Lush7LYefvWEAYP4fgTrQzg4KQOSUR0Ugp+V3Ykph3H
    RZ19kQ+K1I6qKIwc1DGQV/hu1wErSxyL2hTUst+2r4p4pDHZyz4Oux+33IiIcj43
    +2RlxUxurqMCgYEAw7FlcZfLWtInk54jiF2EYwIoQr7JvZOzKc8DCqJIv4DFLNpg
    Lzt13Q13fhMS4D1X99E2N+xUBm3ZfbC3RqAVYXBJEOY/+bGhGAznZX5bp4c9VvMy
    nlc+V48mgq0dq+Bts4nip1d3oqVTH1p39ThrEnnqGAqFL7yLITM7FkcHnXUCgYAB
    JFlpn4kX4hQrHxn76bavehXnWm7Xyw/h1LhCkgz7w4cZ5PSXSRBrY4W8ytNeFCi/
    vyfIkumVh2B39pPTKy/dTgu65OncnHxhDBiV4Zts2Jxewf9J0EvBAYWYKXtKTAMp
    tbwqegdq5qMbONqzr8NmiQrdWRRAaajf4WbVBD/tPQKBgBziVtXkArbEUM9Zruzy
    u9OONjcJX4QrIsEgFFwj9xChezRZj0cOshjIVsVgEoJjF1ICn9rMzvR4TnuWMCH3
    /y30sOwXMb8LjNKdbWr6LhXFYtDvPRPdBmMWJJRYsqkef1qtRzhEIdbDj1Ed9l3w
    VXBSa7XfhDRpOnVCrGz2xZ6F
    -----END PRIVATE KEY-----
  key.manager.secret.id.pem: |
    -----BEGIN CERTIFICATE-----
    MIID5TCCAs2gAwIBAgIUVK/4a0TK/7OlzcvHj28YIYor004wDQYJKoZIhvcNAQEL
    BQAwgYExNjA0BgNVBAMMLWlnLWFsYi0xMzk5NzU1MTYwLnVzLWVhc3QtMS5lbGIu
    YW1hem9uYXdzLmNvbTESMBAGA1UECwwJYW1hem9uYXdzMQwwCgYDVQQKDANjb20x
    CzAJBgNVBAcMAmZyMQswCQYDVQQIDAJmcjELMAkGA1UEBhMCZnIwHhcNMjMwNjAx
    MTQyNjExWhcNMzMwNTI5MTQyNjExWjCBgTE2MDQGA1UEAwwtaWctYWxiLTEzOTk3
    NTUxNjAudXMtZWFzdC0xLmVsYi5hbWF6b25hd3MuY29tMRIwEAYDVQQLDAlhbWF6
    b25hd3MxDDAKBgNVBAoMA2NvbTELMAkGA1UEBwwCZnIxCzAJBgNVBAgMAmZyMQsw
    CQYDVQQGEwJmcjCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBAOL+tmeD
    hmjCWuKNVWnJTPzGFGvtVgYXk4Q0329RsBszZotZCxijLzwzJVvZ13pFzSlstjJp
    5jpv03JrTH8vdxljRl5FVnS5iHuTIc3jcePEnc57M6/YvO1mP+wSULazucHHE74n
    QZBO1Gmne73oA2n7eA6sWUP4fuzj3IrQgpVX38At5oVfafH2thkQMGj7ugT0oB5i
    eulpbElrC0reDlit/MN3flI9OcY7uThiCvH5AP/i+0Z0Anzq6IdwyXfN5TZiv0Rc
    NhOvWCTo53orCmPrfMIryZ95geuVh7Y4yYtaOdcHvXIG7KFSpEQqaUnKvkx/w5+n
    zOSQ+1i2nSaO72cCAwEAAaNTMFEwHQYDVR0OBBYEFKSKY9i6NEHqxS367eVxzeYp
    9BtSMB8GA1UdIwQYMBaAFKSKY9i6NEHqxS367eVxzeYp9BtSMA8GA1UdEwEB/wQF
    MAMBAf8wDQYJKoZIhvcNAQELBQADggEBAJQHugBxgeDTjRRsQXyogO9b1GiS8Awr
    ne6Vs4OBwL2xFpqdf7vxHOxOQKutD7ZLe66dmmUjZx9P4JF/laZGsBGzV8Zwn845
    GBi7jOX6gWpGAp3A8BnEMY5FCdNT9BaLTJcSUNzrcl0D3JA1ni6KBJdNzsqR6wWX
    WAm84NHfkQ62oIz2jXFEakg2uvva5FMHZZQGLYvawJnSO6cmcgahzhVLN8uJP7hT
    X2r230fUOHnkp8OQ2PcikyEOAZ767QrY7RO2DXOEabpj0I7CRqU9rmuyr4eiaGqc
    Bwqww7+a4v/Z2kNzJZdlBlYhwqNIP7RW45cD+GDICom1PY9m3eLJemA=
    -----END CERTIFICATE-----
    -----BEGIN PRIVATE KEY-----
    MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQDi/rZng4Zowlri
    jVVpyUz8xhRr7VYGF5OENN9vUbAbM2aLWQsYoy88MyVb2dd6Rc0pbLYyaeY6b9Ny
    a0x/L3cZY0ZeRVZ0uYh7kyHN43HjxJ3OezOv2LztZj/sElC2s7nBxxO+J0GQTtRp
    p3u96ANp+3gOrFlD+H7s49yK0IKVV9/ALeaFX2nx9rYZEDBo+7oE9KAeYnrpaWxJ
    awtK3g5YrfzDd35SPTnGO7k4Ygrx+QD/4vtGdAJ86uiHcMl3zeU2Yr9EXDYTr1gk
    6Od6Kwpj63zCK8mfeYHrlYe2OMmLWjnXB71yBuyhUqREKmlJyr5Mf8Ofp8zkkPtY
    tp0mju9nAgMBAAECggEBANopqg+kxiqrGQSCh6PLV9XdXkU4bqQeRqYa1t+7aAFM
    jnLBGrwMIlq+YVp87O7UZVE57YZYZ3Ckh1mBrJzUdqgM1NXH2EcJBhaWmzexMIWT
    M4P+vvdz3GhiDG+MTsy5wX9vIRdxzT6vtNDyqigj9BwJFyMrHAQKsZpliVJVAhwa
    8C0/8GVEEqCsmIsDj5ZGEcUwIc7sIdR1XSNQfpcQuZBPEOZl0E8hcqJzUWyW8SOp
    1JNy6VzVXYoG0qYAscyE2dWusGTiTDS9oAtKtj5YIRgdBHaSbie/frG6c/b8EX00
    Re/0Xp+Tg9YI9qXGCuW68A+ay8A6zm3jOuOZfFO2X8kCgYEA9uhiJo6BuHm5vQzV
    oeGOOUWIRZ/3TtaPYHxXAXDTGv2sE3SWmj/yjsFJrG98pI2bKL/itfFDesNLp6Il
    lNJ3P0Pm8w8y5WiuCvDzXEPNRAMyq65pbYFU4xyXJ9XGRc62j4FjaJZ9sk1lTGJt
    niHSFzfO19dB493tw2vAtL9kXG0CgYEA61qcJ2ee7Z9wD4NOGYSBw3A0riho1g/W
    23P/bbwErkxeh0p0HlBD/Lush7LYefvWEAYP4fgTrQzg4KQOSUR0Ugp+V3Ykph3H
    RZ19kQ+K1I6qKIwc1DGQV/hu1wErSxyL2hTUst+2r4p4pDHZyz4Oux+33IiIcj43
    +2RlxUxurqMCgYEAw7FlcZfLWtInk54jiF2EYwIoQr7JvZOzKc8DCqJIv4DFLNpg
    Lzt13Q13fhMS4D1X99E2N+xUBm3ZfbC3RqAVYXBJEOY/+bGhGAznZX5bp4c9VvMy
    nlc+V48mgq0dq+Bts4nip1d3oqVTH1p39ThrEnnqGAqFL7yLITM7FkcHnXUCgYAB
    JFlpn4kX4hQrHxn76bavehXnWm7Xyw/h1LhCkgz7w4cZ5PSXSRBrY4W8ytNeFCi/
    vyfIkumVh2B39pPTKy/dTgu65OncnHxhDBiV4Zts2Jxewf9J0EvBAYWYKXtKTAMp
    tbwqegdq5qMbONqzr8NmiQrdWRRAaajf4WbVBD/tPQKBgBziVtXkArbEUM9Zruzy
    u9OONjcJX4QrIsEgFFwj9xChezRZj0cOshjIVsVgEoJjF1ICn9rMzvR4TnuWMCH3
    /y30sOwXMb8LjNKdbWr6LhXFYtDvPRPdBmMWJJRYsqkef1qtRzhEIdbDj1Ed9l3w
    VXBSa7XfhDRpOnVCrGz2xZ6F
    -----END PRIVATE KEY-----
kind: ConfigMap
metadata:
  name: ig-certificates
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: ig
    app.kubernetes.io/component: ig
    app.kubernetes.io/instance: ig
    app.kubernetes.io/name: ig
    app.kubernetes.io/part-of: forgerock
    tier: middle
  name: ig
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ig
      app.kubernetes.io/component: ig
      app.kubernetes.io/instance: ig
      app.kubernetes.io/name: ig
      app.kubernetes.io/part-of: forgerock
      tier: middle
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "false"
      creationTimestamp: null
      labels:
        app: ig
        app.kubernetes.io/component: ig
        app.kubernetes.io/instance: ig
        app.kubernetes.io/name: ig
        app.kubernetes.io/part-of: forgerock
        tier: middle
    spec:
      volumes:
      - name: ig-volume
        configMap:
          name: ig-certificates
      containers:
      - env:
        - name: AGENT_SECRET_ID
          valueFrom:
            secretKeyRef:
              name: agent-secret-id
              key: password
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        - name: MY_POD_IP
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: status.podIP
        envFrom:
        - secretRef:
            name: openig-secrets-env
        image: devforge1/ig:v2023-v4-sample
        imagePullPolicy: Always
        name: ig
        volumeMounts:
        - name: ig-volume
          mountPath: /var/ig/secrets
        securityContext:
          capabilities:
            add:
            - NET_ADMIN
        ports:
        - containerPort: 8080
          protocol: TCP
        resources:
          requests:
            cpu: 200m
            memory: 512Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext:
        runAsGroup: 0
        runAsUser: 11111
      terminationGracePeriodSeconds: 30
      hostNetwork: true
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: ig
    app.kubernetes.io/component: ig
    app.kubernetes.io/instance: ig
    app.kubernetes.io/name: ig
    app.kubernetes.io/part-of: forgerock
    tier: middle
  name: ig
spec:
  ipFamilies:
  - IPv6
  ipFamilyPolicy: PreferDualStack
  ports:
  - name: ig
    port: 8443
    protocol: TCP
    targetPort: 8080
  selector:
    app: ig
    app.kubernetes.io/component: ig
    app.kubernetes.io/instance: ig
    app.kubernetes.io/name: ig
    app.kubernetes.io/part-of: forgerock
    tier: middle
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/ip-address-type: dualstack
    alb.ingress.kubernetes.io/load-balancer-name: ig-alb
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 8080}, {"HTTP": 8443}]'
    alb.ingress.kubernetes.io/tags: Purpose=lab,ApplicationIDName=frig-dev,RSMs=X265140,BusinessUnit=gtcto,CostCenter=713104,__Exception-ELBLogging=0123
    alb.ingress.kubernetes.io/group.name: ig-group
    alb.ingress.kubernetes.io/healthy-threshold-count: '2'
    alb.ingress.kubernetes.io/unhealthy-threshold-count: '2'
    alb.ingress.kubernetes.io/healthcheck-timeout-seconds: '8'
    alb.ingress.kubernetes.io/healthcheck-interval-seconds: '30'
    alb.ingress.kubernetes.io/healthcheck-path: /
    alb.ingress.kubernetes.io/healthcheck-port: '8443'
    alb.ingress.kubernetes.io/healthcheck-protocol: HTTP
    alb.ingress.kubernetes.io/success-codes: '200'
  name: ig
spec:
  ingressClassName: alb
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: ig
                port:
                  number: 8443
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  creationTimestamp: null
  name: ig
spec:
  maxReplicas: 4
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: ig
  targetCPUUtilizationPercentage: 70
status:
  currentReplicas: 0
  desiredReplicas: 0
