apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: {{ .Values.appName }}
    app.kubernetes.io/component: {{ .Values.appName }}
    app.kubernetes.io/instance: {{ .Values.appName }}
    app.kubernetes.io/name: {{ .Values.appName }}
    app.kubernetes.io/part-of: forgerock
    tier: middle
  name: {{ .Values.appName }}
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.appName }}
      app.kubernetes.io/component: {{ .Values.appName }}
      app.kubernetes.io/instance: {{ .Values.appName }}
      app.kubernetes.io/name: {{ .Values.appName }}
      app.kubernetes.io/part-of: forgerock
      tier: middle
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "false"
      creationTimestamp: null
      labels:
        app: {{ .Values.appName }}
        app.kubernetes.io/component: {{ .Values.appName }}
        app.kubernetes.io/instance: {{ .Values.appName }}
        app.kubernetes.io/name: {{ .Values.appName }}
        app.kubernetes.io/part-of: forgerock
        tier: middle
    spec:
      containers:
      - env:
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        - name: MY_POD_IP
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: status.podIP
        envFrom:
        - secretRef:
            name: openig-secrets-env
        #image: devforge1/ig:v2023-v5-sample
        image: gcr.io/forgerock-io/ig@sha256:f98027c534652a9356e796b541e9c460f47db9a96c5733fcae6cdabb40ca9b7d
        imagePullPolicy: Always
        livenessProbe:
          httpGet:
            host:
            scheme: HTTP
            path: /
            port: 8080
            httpHeaders:
            - name: Host
              value: status.podIP
          initialDelaySeconds: 5
          periodSeconds: 5
          successThreshold: 1
          timeoutSeconds: 1
          failureThreshold: 1
        name: ig
        securityContext:
          capabilities:
            add:
            - NET_ADMIN
        ports:
        - containerPort: 8080
          protocol: TCP
        readinessProbe:
          httpGet:
            host:
            scheme: HTTP
            path: /
            port: 8080
            httpHeaders:
            - name: Host
              value: status.podIP
          failureThreshold: 1
          initialDelaySeconds: 5
          periodSeconds: 10
        resources:
          requests:
            cpu: 200m
            memory: 512Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext:
        runAsGroup: 0
        runAsUser: 11111
      terminationGracePeriodSeconds: 30
      hostNetwork: true