---
- name: Install Docker
  yum: 
    name: '{{item}}'
    state: present
  with_items:
  - yum-utils  
  - device-mapper-persistent-data
  - lvm2

- name: Generate docker-ce.repo file
  command: "yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo"

- name: Install Docker
  yum: 
    name: docker-ce
    state: present

- name: Start docker service
  service:
    name: docker
    state: started

- name: Enable docker service
  service:
    name: docker
    enabled: yes

- name: Generate /etc/yum.repos.d/kubernetes.repo file
  template:
    src: kubernetes.repo.j2
    dest: /etc/yum.repos.d/kubernetes.repo

- name: Install Kubernetes
  yum: 
    name: '{{item}}'
    state: present
  with_items:
  - kubelet
  - kubeadm
  - kubectl

- name: Enable kubelet service
  service:
    name: kubelet
    enabled: yes

- name: Start kubelet service
  service:
    name: kubelet
    state: started

- name: Generate /etc/hosts file
  template:
    src: hosts.j2
    dest: /etc/hosts

- name: Generate /etc/sysctl.d/k8s.conf file
  template:
    src: kubernetes.conf.j2
    dest: /etc/sysctl.d/k8s.conf

- name: Reload service daemon
  command: "sysctl --system"

- name: Set Enforce 0
  command: "setenforce 0"
    
- name: Modify SELINUX to permissive
  lineinfile:
    path: /etc/selinux/config
    regexp: '^SELINUX=enforcing'
    line: SELINUX=disabled

- name: Disable SWAP in fstab since kubernetes can't work with swap enabled (1/2)
  replace:
    path: /etc/fstab
    regexp: '^([^#].*?\sswap\s+sw\s+.*)$'
    replace: '# \1'

- name: Disable SWAP since kubernetes can't work with swap enabled (2/2)
  command: "swapoff -a"

- name: Add KUBELET_EXTRA_ARGS
  lineinfile:
    dest: /usr/lib/systemd/system/kubelet.service.d/10-kubeadm.conf
    line: "Environment=\"KUBELET_EXTRA_ARGS=--fail-swap-on=false\""
    insertafter: '[Service]'