apiVersion: v1
kind: ServiceAccount
metadata: 
  name: pod-viewer-sa
  namespace: auth 
automountServiceAccountToken: true 
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role 
metadata:
  name: pod-viewer-role
  namespace: auth 
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pod-viewer-rb
  namespace: auth 
roleRef: 
  apiGroup: rbac.authorization.k8s.io
  kind: Role 
  name: pod-viewer-role
subjects:
- kind: ServiceAccount
  name: pod-viewer-sa
  namespace: auth 