---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: opensource 
    app.kubernetes.io/component: opensource 
    app.kubernetes.io/instance: opensource 
    app.kubernetes.io/name: opensource 
  name: opensource 
spec:
  ipFamilies:
  - IPv6
  ipFamilyPolicy: SingleStack
  ports:
  - name: opensource 
    port: 80
    protocol: TCP
    targetPort: 8089
  selector:
    app: opensource 
    app.kubernetes.io/component: opensource 
    app.kubernetes.io/instance: opensource 
    app.kubernetes.io/name: opensource 
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: opensource 
    app.kubernetes.io/component: opensource 
    app.kubernetes.io/instance: opensource 
    app.kubernetes.io/name: opensource 
  name: opensource 
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: opensource 
      app.kubernetes.io/component: opensource 
      app.kubernetes.io/instance: opensource 
      app.kubernetes.io/name: opensource 
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "false"
      creationTimestamp: null
      labels:
        app: opensource 
        app.kubernetes.io/component: opensource 
        app.kubernetes.io/instance: opensource 
        app.kubernetes.io/name: opensource 
    spec:
      volumes:
      - name: kubeconfig-volume
        configMap:
          name: kubeconfig
      containers:
      - env:
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        - name: MY_POD_IP
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: status.podIP      
        image: devforge1/hardeneks:v2
        volumeMounts:
        - name: kubeconfig-volume
          mountPath: /home/locust/.kube/
        imagePullPolicy: Always
        name: opensource 
        securityContext:
          capabilities:
            add:
            - NET_ADMIN
        ports:
        - containerPort: 8089
          protocol: TCP
        - containerPort: 5557
          protocol: TCP
        resources:
          requests:
            cpu: 200m
            memory: 512Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext:
        runAsGroup: 0
        runAsUser: 11111
      terminationGracePeriodSeconds: 30
      hostNetwork: true