---
- name: Set up kubeadm
  shell: kubeadm init --pod-network-cidr=10.201.0.0/16 --service-cidr=10.100.0.0/16 --service-dns-domain="kubernetes.lab" --ignore-preflight-errors=Mem --ignore-preflight-errors=NumCPU

- name: Create directories kube
  file: 
    path: /root/.kube 
    state: directory 
    owner: root 
    group: root

- name: Configure kube
  copy: 
    src: /etc/kubernetes/admin.conf 
    dest: /root/.kube/config 
    remote_src: yes 
    owner: root 
    group: root

# - name: restart server
#   shell: 'sleep 1 && shutdown -r now "Reboot triggered by Ansible" && sleep 1'
#   async: 1
#   poll: 0
#   become: true

# - name: Wait for server to restart {{ inventory_hostname }}
#   local_action:
#     module: wait_for
#       host={{ inventory_hostname }}
#       port={{ ansible_ssh_port }}
#       delay=10
#     become: false

- name: Generate /etc/hosts file
  template:
    src: hosts.j2
    dest: /etc/hosts

# - name: Generate Calico Drivers YAML file
#   template:
#     src: calico.yaml.j2
#     dest: /tmp/calico.yaml

# - name: Install Calico Drivers
#   shell: |
#     kubectl apply -f /tmp/calico.yaml