---
- name: Set up kubeadm
  shell: kubeadm init --pod-network-cidr=10.201.0.0/16 --service-cidr=10.100.0.0/16 --service-dns-domain="kubernetes.lab" --ignore-preflight-errors=Mem --ignore-preflight-errors=NumCPU

- name: Create directories kube
  file: 
    path: /root/.kube 
    state: directory 
    owner: root 
    group: root

- name: Configure kube
  copy: 
    src: /etc/kubernetes/admin.conf 
    dest: /root/.kube/config 
    remote_src: yes 
    owner: root 
    group: root

- name: Configure kube
  shell: |
    kubectl create -f https://raw.githubusercontent.com/projectcalico/calico/v3.25.0/manifests/tigera-operator.yaml

# - name: Generate /etc/hosts file
#   template:
#     src: hosts.j2
#     dest: /etc/hosts