---
- name: Set up kubeadm
  shell: kubeadm init --pod-network-cidr=10.200.0.0/16 --service-cidr=10.100.0.0/16 --service-dns-domain="kubernetes.lab" --ignore-preflight-errors=Mem --ignore-preflight-errors=NumCPU

- name: Create directories kube
  file: 
    path: /root/.kube 
    state: directory 
    owner: root 
    group: root

- name: Configure kube
  copy: 
    src: /etc/kubernetes/admin.conf 
    dest: /root/.kube/config 
    remote_src: yes 
    owner: root 
    group: root

- name: Copy weave kube
  template: 
    src: calico.yml.j2 
    dest: /tmp/calico.yml

- name: Configure kube
  shell: kubectl apply -f /tmp/calico.yml

# - name: Generate /etc/hosts file
#   template:
#     src: hosts.j2
#     dest: /etc/hosts

- name: Update the /etc/hosts file with node name
  lineinfile:
  path: "/etc/hosts"
    regexp: ".*\t{{ hostvars[item]['ansible_hostname']}}\t{{ hostvars[item]['ansible_hostname']}}"
    line: "{{ hostvars[item]['ansible_env'].SSH_CONNECTION.split(' ')[2] }}\t{{ hostvars[item]['ansible_hostname']}}\t{{ hostvars[item]['ansible_hostname']}}"
    state: present
    backup: yes
#  when: ansible_hostname != "{{ item }}" or ansible_hostname == "{{ item }}"
  with_items: "{{groups['kubernetes']}}"