---
# - name: Kubeadm init 
#   shell: "sudo kubeadm init --pod-network-cidr=192.168.0.0/16 --cri-socket=/run/containerd/containerd.sock --ignore-preflight-errors=Mem --ignore-preflight-errors=NumCPU"
#   when:
#     - inventory_hostname in groups['kubernetes_master']

# - name: Create a directory $HOME/.kube if it does not exist
#   file:
#     path: $HOME/.kube
#     state: directory

# - name: Copy file with owner and permissions
#   copy:
#     src: /etc/kubernetes/admin.conf 
#     dest: $HOME/.kube/config
#     owner: cloud_user
#     group: cloud_user
#     mode: '0775'
#   when:
#   - inventory_hostname in groups['kubernetes_master']

- name: Copy /etc/kubernetes/admin.conf to $HOME/.kube/config
  shell: "sudo cp -i /etc/kubernetes/admin.conf $HOME/.kube/config"

- name: Change permission of $HOME/.kube/config
  shell: "sudo chown $(id -u):$(id -g) $HOME/.kube/config"

- name: Install the Tigera Calico operator
  command: "kubectl create -f https://raw.githubusercontent.com/projectcalico/calico/v3.25.1/manifests/tigera-operator.yaml"
  # when:
  #   - inventory_hostname in groups['kubernetes_master']

- name: Install the custom resource definitions
  command: "kubectl create -f https://raw.githubusercontent.com/projectcalico/calico/v3.25.1/manifests/custom-resources.yaml"
  # when:
  #   - inventory_hostname in groups['kubernetes_master']