apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: dev-role
  namespace: development
rules:
- apiGroups:
  - ""
  - apps
  - batch
  - extensions
  resources:
  - configmaps
  - cronjobs
  - deployments
  - events
  - ingresses
  - jobs
  - pods
  - pods/attach
  - pods/exec
  - pods/log
  - pods/portforward
  - secrets
  - services
  verbs:
  - create
  - delete
  - describe
  - get
  - list
  - patch
  - update