apiVersion: v1
kind: PersistentVolume
metadata:
  name: aqua-audit-db-pv
  namespace: aqua 
spec:
  capacity:
    storage: 50Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: gp2
  awsElasticBlockStore:
    fsType: ext4
    volumeID: vol-0eb09561b33c7fb79
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: aqua-db-pv
  namespace: aqua 
spec:
  capacity:
    storage: 50Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: gp2
  awsElasticBlockStore:
    fsType: ext4
    volumeID: vol-071502628aaba4d78
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: aqua-db-pvc
  namespace: aqua 
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
  volumeName: aqua-audit-db-pv
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: aqua-audit-db-pvc
  namespace: aqua 
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
  volumeName: aqua-db-pv