---
- name: Generate Token kubeadm
  shell: |
    kubeadm token create --print-join-command
  register: kubernetes_token
  when:
    - inventory_hostname in groups['kubernetes']|default([])

- debug:
    msg: "{{ item.stderr }}"
  loop: 
    - "{{ kubernetes_token.results }}"

# - name: Join nodes
#   shell: |
#     "{{ kubernetes_token.results }}"
#   when:
#     - inventory_hostname in groups['kubernetes_nodes']|default([])