---
- name: Generate Token kubeadm
  shell: |
    kubeadm token create --print-join-command
  register: kubernetes_token
  when:
    - inventory_hostname in groups['kubernetes']

- debug:
    msg: "{{ kubernetes_token..stdout_lines[0] }}"

# - name: Join nodes
#   shell: |
#     "{{ kubernetes_token.results }}"
#   when:
#     - inventory_hostname in groups['kubernetes_nodes']|default([])