pipeline {
    agent any

    environment {
        TF_VERSION = "1.5.7"
        TF_WORKSPACE = "default"
        TF_DIR = "./terraform/aws-s3"
    }

    stages {
        stage("Checkout") {
            steps {
                checkout scm
            }
        }
        stage("Terraform Init") {
            steps {
                dir("${env.TF_DIR}") {
                    sh "terraform init"
                }
            }
        }
        stage("Terraform Validate") {
            steps {
                dir("${env.TF_DIR}") {
                    sh "terraform validate"
                }
            }
        }
        stage("Terraform Format") {
            steps {
                dir("${env.TF_DIR}") {
                    sh "terraform fmt -check"
                }
            }
        }
        stage("Terraform Plan") {
            steps {
                dir("${env.TF_DIR}") {
                    withCredentials([[ $class: "AmazonWebServicesCredentialsBinding", credentialsId: "aws-playground" ]]) {
                        sh """
                            terraform plan \
                            -var "access-key=${AWS_ACCESS_KEY_ID}" \
                            -var "secret-key=${AWS_SECRET_ACCESS_KEY}" \
                            -out=tfplan
                        """
                    }
                }
            }
        }
        stage("Terraform Apply") {
            steps {
                dir("${env.TF_DIR}") {
                    input message: "Approve Terraform Apply?"
                    sh "terraform apply -auto-approve tfplan"
                }
            }
        }
    }

    post {
        always {
            cleanWs()
        }
    }
}