apiVersion: v1
kind: Pod
metadata:
  name: immutability-pod
spec:
  containers:
  - name: nginx
    image: nginx:1.14.2
    # Use readOnlyRootFilesystem: true to enforce this. A container without this setting might not be considered immutable
    securityContext:
      #privileged: true 
      privileged: false 
      #allowPrivilegedEscalation: true 
      allowPrivilegedEscalation: false
      #runAsUser: 0
      runAsUser: 1000
      #readOnlyRootFilesystem: false
      readOnlyRootFilesystem: true
    volumeMounts:
    - name: cache 
      mountPath: /var/cache/nginx
    - name: run 
      mountPath: /var/run 
  # If the application does need to write data, use volume mounts to support this
  volumes:
  - name: cache 
    emptyDir: {} 
  - name: run 
    emptyDir: {} 