---
- name: Install pre-requisites
  apt: 
    name: '{{item}}'
    state: present
  with_items:
  - curl
  - apt-transport-https

- name: Add the Kubernetes APT key
  apt_key: 
    url: https://packages.cloud.google.com/apt/doc/apt-key.gpg 
    state: present

- name: Add the Kubernete source to the APT source list
  apt_repository: 
    repo: 'deb http://apt.kubernetes.io/ kubernetes-{{ansible_distribution_release}} main' 
    state: present

- name: Install Docker
  apt: 
    name: docker.io
    state: present

- name: Enable service docker state
  service:
    name: docker
    enabled: true

- name: Start docker service
  service:
    name: docker
    state: started

- name: Install Kubernetes
  apt: 
    name: '{{item}}'
    state: present
  with_items:
  - kubelet
  - kubeadm
  - kubectl
  - kubernetes-cni

- name: Prevent kubectl, kubeadm, and kubelet from being upgraded
  dpkg_selections:
    name: '{{item}}'
    selection: hold
  with_items:
  - kubelet
  - kubeadm
  - kubectl

- name: Disable SWAP since kubernetes can't work with swap enabled (1/2)
  shell: |
    swapoff -a 
  when:
    - inventory_hostname in groups['kubernetes']

- name: Disable SWAP in fstab since kubernetes can't work with swap enabled (2/2)
  replace:
    path: /etc/fstab
    regexp: '^([^#].*?\sswap\s+sw\s+.*)$'
    replace: '# \1'
  when:
    - inventory_hostname in groups['kubernetes']

- name: Iptables See Bridged Traffic
  shell: |
    sysctl net.bridge.bridge-nf-call-iptables=1 
  when:
    - inventory_hostname in groups['kubernetes']

- name: Generate /etc/hosts file
  template:
    src: daemon.j2
    dest: /etc/docker/daemon.json

- name: Reload service daemon
  systemd:
    name: daemon-reload
    state: reloaded

- name: Restart docker service
  service:
    name: docker
    state: restarted
