apiVersion: apps/v1
kind: Deployment
metadata:
  name: static-analysis-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: static-analysis-deployment
  template:
    metadata:
      labels:
        app: static-analysis-deployment
    spec:
      # Avoid the use of host namespaces 
      #hostIPC: true
      hostIPC: false
      #hostNetwork: true
      hostNetwork: false
      #hostPID: true
      hostPID: false
      containers:
      - name: nginx
        # Avoid the 
        #image: nginx:latest
        image: nginx:1.19.10
        ports:
        - containerPort: 80
        securityContext:
          #privileged: true
          privileged: false