apiVersion: audit.k8s.io/v1
kind: Policy
rules:
- level: RequestResponse
  resources:
  - groups: ""
    resources: ["namespaces"]
- level: Request
  resources:
  - groups: ""
    resources: ["pods", "services"]
  namespaces: ["web"]
- level: Metadata
  resources:
  - groups: ""
    resources: ["secrets"]
- level: Metadata