apiVersion: v1
kind: Pod
metadata:
  name: apparmor-disk-write
  annotations:
    # k8s-deny-write is the name of the apparmor profile 
    # after slash we should use the container name e.g. test-pod
    container.apparmor.security.beta.kubernetes.io/busyboxg: localhost/k8s-deny-write
spec:
  containers:
  - name: busybox
    image: busybox
    command: ['sh', '-c', 'while true; do echo "I write to the disk!" > diskwrite.log; sleep 5; done']
    