apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.appName }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.appName }}
spec:
  replicas: {{ .Values.spec.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.appName }}
      tier: frontend
  template:
    metadata:
      labels:
        app: {{ .Values.appName }}
        tier: frontend
    spec:
      containers:
      - name: {{ .Values.appName }}-container
        image: "{{ .Values.image.name }}:{{ .Values.image.tag }}"
        ports:
        - containerPort: {{ .Values.spec.containerPort }}
        envFrom:
        - configMapRef:
            name: {{ .Values.configmap.name }}
        resources:
          requests:
            memory: {{ .Values.spec.resources.requests.memory }}
            cpu: {{ .Values.spec.resources.requests.cpu }}
          limits:
            memory: {{ .Values.spec.resources.limits.memory }}
            cpu: {{ .Values.spec.resources.limits.cpu }}
