---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: opensource 
    app.kubernetes.io/component: opensource 
    app.kubernetes.io/instance: opensource 
    app.kubernetes.io/name: opensource 
  name: opensource 
spec:
  ipFamilies:
  - IPv6
  ipFamilyPolicy: SingleStack
  ports:
  - name: opensource 
    port: 80
    protocol: TCP
    targetPort: 8089
  selector:
    app: opensource 
    app.kubernetes.io/component: opensource 
    app.kubernetes.io/instance: opensource 
    app.kubernetes.io/name: opensource 
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: opensource 
    app.kubernetes.io/component: opensource 
    app.kubernetes.io/instance: opensource 
    app.kubernetes.io/name: opensource 
  name: opensource 
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: opensource 
      app.kubernetes.io/component: opensource 
      app.kubernetes.io/instance: opensource 
      app.kubernetes.io/name: opensource 
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "false"
      creationTimestamp: null
      labels:
        app: opensource 
        app.kubernetes.io/component: opensource 
        app.kubernetes.io/instance: opensource 
        app.kubernetes.io/name: opensource 
    spec:
      volumes:
      - name: kubeconfig-volume
        configMap:
          name: kubeconfig
      containers:
      - env:
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        - name: MY_POD_IP
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: status.podIP      
        image: devforge1/hardeneks:v2
        volumeMounts:
        - name: kubeconfig-volume
          mountPath: /home/locust/.kube/
        imagePullPolicy: Always
        name: opensource 
        securityContext:
          capabilities:
            add:
            - NET_ADMIN
        ports:
        - containerPort: 8089
          protocol: TCP
        - containerPort: 5557
          protocol: TCP
        resources:
          requests:
            cpu: 200m
            memory: 512Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext:
        runAsGroup: 0
        runAsUser: 11111
      terminationGracePeriodSeconds: 30
      hostNetwork: true
--- 
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    # LOAD BALANCER
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/ip-address-type: dualstack
    alb.ingress.kubernetes.io/load-balancer-name: opensource-alb
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 8080}, {"HTTP": 80}, {"HTTPS": 443}, {"HTTPS": 8443}]' #'[{"HTTP": 8080}]'
    alb.ingress.kubernetes.io/tags: Purpose=lab
    alb.ingress.kubernetes.io/group.name: opensource-group
    alb.ingress.kubernetes.io/certificate-arn: "arn:aws:acm:us-east-1:697538654983:certificate/d6b56190-df17-4a01-a96c-bdef3dc4aea5"
    alb.ingress.kubernetes.io/ssl-policy: ELBSecurityPolicy-TLS-1-1-2017-01
    alb.ingress.kubernetes.io/healthy-threshold-count: '2'
    alb.ingress.kubernetes.io/unhealthy-threshold-count: '2'
    alb.ingress.kubernetes.io/healthcheck-timeout-seconds: '8'
    alb.ingress.kubernetes.io/healthcheck-interval-seconds: '30'
    alb.ingress.kubernetes.io/healthcheck-path: /
    alb.ingress.kubernetes.io/healthcheck-port: '8089'
    alb.ingress.kubernetes.io/healthcheck-protocol: HTTP
    alb.ingress.kubernetes.io/success-codes: '200'
  name: opensource
spec:
  ingressClassName: alb
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: opensource
                port:
                  number: 80