# - name: Install kubernetes 
#   hosts: kubernetes_nodes
#   roles:
#     - { role: ../kubernetes }

- name: Join cluster kubernetes 
  hosts: kubernetes_acg, kubernetes_acg_nodes
  roles:
    - { role: ../kubernetes-nodes }